name: Python Lint

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-24.04
    env:
      python: 3.11
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          py_ver=$(echo py${{ env.python }} | tr -d '.')
          ruff check --output-format=github --target-version=${py_ver} ./smb_zfs
