name: Build & Upload Python Package

on:
  release:
    types: [published]

jobs:
  Deploy-to-PyPI:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build --wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  Build-Debian-Package:
    runs-on: ubuntu-24.04
    container: debian:12-slim
    permissions:
      contents: write
    steps:
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y python3-stdeb build-essential devscripts git dh-python

    - name: Checkout code
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git clone ${{ github.repositoryUrl }} .
        git checkout ${{ github.ref_name }}
    - name: Generate Debian source control files
      run: python3 setup.py --command-packages=stdeb.command sdist_dsc

    - name: Create Debian changelog and set version
      env:
        # Set environment variables for dch using the GitHub context
        DEBEMAIL: "github.nstein@mailbox.org"
        DEBFULLNAME: "Nils Stein"
      run: |
        cd deb_dist/smb-zfs-*/
        dch --create --package smb-zfs --newversion "${{ github.ref_name }}-1" "New release."
        # Set debhelper compatibility level to 13 to avoid warnings
        echo 13 > debian/compat

    - name: Build .deb package
      run: |
        cd deb_dist/smb-zfs-*/
        debuild -us -uc

    - name: Upload .deb to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: deb_dist/*.deb
        asset_name: smb-zfs_${{ github.ref_name }}_all.deb
        asset_content_type: application/vnd.debian.binary-package
