name: Build & Upload Python Package

on:
  release:
    types: [published]

jobs:
  Pypi:
    runs-on: ubuntu-24.04
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build --wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
  deb:
    runs-on: ubuntu-24.04
    container: debian:12
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        path: ./src
    - name: Install dependencies
      working-directory: ./src
      run: |
        apt-get update
        apt-get install jq -y
        (type -p wget >/dev/null || (apt-get update && apt-get install wget -y)) \
          && mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && mkdir -p -m 755 /etc/apt/sources.list.d \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt-get update \
          && apt-get install gh -y
        apt-get build-dep . -y
    - name: Update Changelog
      working-directory: ./src
      env:
        GIT_TAG: ${{ github.event.release.tag_name }}
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        gbp dch --new-version="${GIT_TAG}-1" --release --debian-tag="${GIT_TAG}" --spawn-editor=/bin/true --ignore-branch --git-author
    - name: Create Package
      working-directory: ./src
      run: |
        dpkg-buildpackage -us -uc
    - name: Upload binary to release
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_TAG: ${{ github.event.release.tag_name }}
      run: |
        FILES=(python3-smb-zfs_*_all.deb)
        if [[ -f "${FILES[0]}" ]]; then
          gh release upload "${GIT_TAG}" "${FILES[@]}" --clobber
        else
          echo "No matching .deb file found"
          exit 1
        fi
