name: Build & Upload Packages

on:
  release:
    types: [published]

jobs:
  Pypi:
    runs-on: ubuntu-24.04
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build --wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
  Debian:
    runs-on: ubuntu-24.04
    container: debian:12
    permissions:
      contents: write
    steps:
    - name: Install workflow dependencies
      run: |
        apt-get update
        apt-get install -y curl git jq
        # Install latest GitHub CLI
        URL=$(curl -s https://api.github.com/repos/cli/cli/releases/latest \
            | jq -r '.assets[] | select(.name | test("linux_amd64\\.deb$")) | .browser_download_url')
        curl -sL "$URL" -o gh_latest_linux_amd64.deb
        apt install -y ./gh_latest_linux_amd64.deb
    - uses: actions/checkout@v4
      with:
        path: src
        fetch-depth: 0
    - name: Install build dependencies
      working-directory: src
      run: |
        apt-get build-dep . -y
    - name: Update Changelog
      working-directory: src
      env:
        GIT_TAG: ${{ github.event.release.tag_name }}
        GH_TOKEN: ${{ github.token }}
      run: |
        EMAIL="${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        NAME="$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        DATE="$(date -u '+%a, %d %b %Y %H:%M:%S +0000')"

        # Create new changelog entry and prepend it to debian/changelog
        {
          cat <<EOF
        smb-zfs (${GIT_TAG}-1) stable; urgency=medium

          * Release ${GIT_TAG}: https://github.com/${GITHUB_ACTOR}/smb-zfs/releases/tag/${GIT_TAG}

        -- ${NAME} <${EMAIL}>  ${DATE}

        EOF
          cat debian/changelog
        } > debian/changelog.new && mv debian/changelog.new debian/changelog
    - name: Create Package
      working-directory: src
      run: |
        dpkg-buildpackage -us -uc
    - name: Attach debian package to release
      working-directory: src
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_TAG: ${{ github.event.release.tag_name }}
      run: |
        gh release upload "${GIT_TAG}" "../python3-smb-zfs_${GIT_TAG}-1_all.deb" --clobber
    - name: Push release changelog to main
      working-directory: src
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_TAG: ${{ github.event.release.tag_name }}
      run: |
        # Configure git
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"

        git switch main
        git add debian/changelog
        git commit -m "Changelog release ${GIT_TAG}"
        git pull -r
        git push
